const VANILLA = "COFFEE_FLAVOR_VANILLA";
const CARAMEL = "COFFEE_FLAVOR_CARAMEL";
const PSL = "COFFEE_FLAVOR_PSL";
const MOCHA = "COFFEE_FLAVOR_MOCHA";
const HAZELNUT = "COFFEE_FLAVOR_HAZELNUT";

module.exports = {
  VANILLA,
  CARAMEL,
  PSL,
  MOCHA,
  HAZELNUT,
};
